project:
  type: website

website:
  page-navigation: true
  title: "ISSS624-Applied Geo-spatial Analytics"
  
  sidebar: 
    logo: "images/geospatial_icon.jpg"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/dneoo/ISSS624
        text: "Github"
      - icon: bar-chart-fill
        href: https://public.tableau.com/app/profile/dabbie.neo
        text: "Tableau"
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "About this website"
        contents: 
          - text: Home
            href: index.qmd
          - text: About
            href: about.qmd
      - section: "Hands-on Exercise"
        contents: 
          - text: "Hands-on Exercise 1A"
            href: "Hands-on_Ex/Hands-on_Ex01A/Hands-on_Ex01A.html"
          - text: "Hands-on Exercise 1B"
            href: "Hands-on_Ex/Hands-on_Ex01B/Hands-on_Ex01B.html"
          - text: "Hands-on Exercise 2A"
            href: "Hands-on_Ex/Hands-on_Ex02A/Hands-on_Ex02A.html"
          - text: "Hands-on Exercise 2B & C"
            href: "Hands-on_Ex/Hands-on_Ex02B/Hands-on_Ex02B&C.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
      - section: "In-Class Exercise"
        contents:
           - text: "In-class Ex 1"
             href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
           - text: "In-class Ex 2"
             href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html" 
           - text: "In-class Ex 3"
             href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
           - text: "In-class Ex 4"
             href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
           - text: "In-class Ex 5"
             href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
      - section: "Take-home Exercise"
        contents: 
          - text: "Take-Home Exercise 1"
            href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"
          - text: "Take-Home Exercise 2"
            href: "Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html"

format:
  html:
    theme: journal
    smooth-scroll: true
    css: styles.css
    toc: true

editor: visual

