---
title: "Hands-on Exercise 2B - Global Measures of Spatial Autocorrelation"
author: "Dabbie Neo"
date: "19 Novemember 2023"
date-modified: "`r Sys.Date()`"
---

# 1. Overview

In this hands-on exercise, we will learn how to compute Global and Local Measure of Spatial Autocorrelation (GLSA) by using **spdep** package. By the end to this hands-on exercise, we will be able to:

-   import geospatial data using appropriate function(s) of **sf** package,

-   import csv file using appropriate function of **readr** package,

-   perform relational join using appropriate join function of **dplyr** package,

-   compute Global Spatial Autocorrelation (GSA) statistics by using appropriate functions of **spdep** package,

    -   plot Moran scatterplot,

    -   compute and plot spatial correlogram using appropriate function of **spdep** package.

-   compute Local Indicator of Spatial Association (LISA) statistics for detecting clusters and outliers by using appropriate functions **spdep** package;

-   compute Getis-Ord\'s Gi-statistics for detecting hot spot or/and cold spot area by using appropriate functions of **spdep** package; and

-   to visualise the analysis output by using **tmap** package.

# 2. Getting Started

In spatial policy, one of the main development objective of the local government and planners is to ensure equal distribution of development in the province. Our task in this study, hence, is to apply appropriate spatial statistical methods to discover if development are evenly distributed geographically. If the answer is **No**. Then, our next question will be \"is there sign of spatial clustering?\". And, if the answer for this question is yes, then our next question will be \"where are these clusters?\"

In this case study, we are interested to examine the spatial pattern of a selected development indicator (i.e. GDP per capita) of *Hunan Provice, People Republic of China (https://en.wikipedia.org/wiki/Hunan).*

## 2.1  Data 

Two data sets will be used in this hands-on exercise, they are:

-   **Hunan province administrative boundary layer at county level.** This is a geospatial data set in ESRI shapefile format.

-   **Hunan_2012.csv**: This csv file contains selected Hunan\'s local development indicators in 2012.

## 2.2 Install and launch R packages
